/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lardeApoio.janelas;

import java.awt.Color;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author beatr
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        lblData = new javax.swing.JLabel();
        tabFicha = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tabCurso = new javax.swing.JTabbedPane();
        jButton3 = new javax.swing.JButton();
        tabVisita = new javax.swing.JTabbedPane();
        jButton4 = new javax.swing.JButton();
        kid1 = new javax.swing.JLabel();
        kid2 = new javax.swing.JLabel();
        kid3 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        cadastro = new javax.swing.JMenu();
        pais = new javax.swing.JMenuItem();
        criança = new javax.swing.JMenuItem();
        mFuncionario = new javax.swing.JMenuItem();
        mRelatorio = new javax.swing.JMenu();
        mAdoçoes = new javax.swing.JMenuItem();
        opçoes = new javax.swing.JMenu();
        Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHILDREAM");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        desktop.setPreferredSize(new java.awt.Dimension(470, 568));

        lblData.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        lblData.setText("Data");

        tabFicha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabFichaMouseClicked(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        tabFicha.addTab("Ficha", jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lardeApoio/icones/profile.jpg"))); // NOI18N
        jButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jButton2ItemStateChanged(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tabCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabCursoMouseClicked(evt);
            }
        });

        jButton3.setText("jButton3");
        tabCurso.addTab("Curso", jButton3);

        tabVisita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabVisitaMouseClicked(evt);
            }
        });

        jButton4.setText("jButton4");
        tabVisita.addTab("Visita", jButton4);

        desktop.setLayer(lblData, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(tabFicha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(tabCurso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(tabVisita, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopLayout.createSequentialGroup()
                        .addGap(0, 398, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(desktopLayout.createSequentialGroup()
                        .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(desktopLayout.createSequentialGroup()
                                .addComponent(tabFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tabCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tabVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(desktopLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addContainerGap(477, Short.MAX_VALUE)
                .addComponent(lblData)
                .addGap(48, 48, 48)
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabFicha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tabCurso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(desktopLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabVisita, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kid1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lardeApoio/icones/child1.png"))); // NOI18N

        kid2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lardeApoio/icones/child2.png"))); // NOI18N

        kid3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lardeApoio/icones/child3.png"))); // NOI18N

        cadastro.setText("Cadastro");
        cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroActionPerformed(evt);
            }
        });

        pais.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        pais.setText("Pais");
        pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisActionPerformed(evt);
            }
        });
        cadastro.add(pais);

        criança.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        criança.setText("Criança");
        criança.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criançaActionPerformed(evt);
            }
        });
        cadastro.add(criança);

        mFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mFuncionario.setText("Funcionario");
        mFuncionario.setEnabled(false);
        mFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mFuncionarioActionPerformed(evt);
            }
        });
        cadastro.add(mFuncionario);

        jMenuBar2.add(cadastro);

        mRelatorio.setText("Relatório");
        mRelatorio.setEnabled(false);

        mAdoçoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        mAdoçoes.setText("Adoçoes");
        mAdoçoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAdoçoesActionPerformed(evt);
            }
        });
        mRelatorio.add(mAdoçoes);

        jMenuBar2.add(mRelatorio);

        opçoes.setText("Opçoes");

        Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        opçoes.add(Sair);

        jMenuBar2.add(opçoes);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kid2)
                    .addComponent(kid1)
                    .addComponent(kid3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kid1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kid2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kid3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(702, 641));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void criançaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criançaActionPerformed
        // TODO add your handling code here:
       TelaCriança crianca = new TelaCriança();
      crianca.setVisible(true);
      desktop.add(crianca);
        
    }//GEN-LAST:event_criançaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // DATA DO SISTEMA IMPORT JAVADATE
           Date data = new Date();
           //SO FUNCIONA SHORT
           DateFormat formatar =  DateFormat.getDateInstance(DateFormat.SHORT);
           //lblData.setText(data.toString());
           lblData.setText(formatar.format(data));
           lblData.setForeground(Color.white);
    }//GEN-LAST:event_formWindowActivated

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        int sair = JOptionPane.showConfirmDialog(null,"Sair?","Atenção",JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
            System.exit(0);   
        }
            //PROPRIEDADES TELA SECUNDARIA  DISPOSE  (DESMARCAR EXIT)  EXIT FECHA O SISTEMA
    }//GEN-LAST:event_SairActionPerformed

    private void mFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mFuncionarioActionPerformed
      TelaFuncionario funcionario = new TelaFuncionario();
      funcionario.setVisible(true);
      desktop.add(funcionario);
      
    }//GEN-LAST:event_mFuncionarioActionPerformed

    private void paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisActionPerformed
        // TODO add your handling code here:
        TelaPais pais = new TelaPais();
        pais.setVisible(true);
        desktop.add(pais);
    }//GEN-LAST:event_paisActionPerformed

    private void cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroActionPerformed

    private void jButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jButton2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Adoção adocao = new Adoção();
        adocao.setVisible(true);
        desktop.add(adocao);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabFichaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabFichaMouseClicked
        // TODO add your handling code here:
        TelaFicha ficha = new TelaFicha();
        ficha.setVisible(true);
        desktop.add(ficha);

    }//GEN-LAST:event_tabFichaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabCursoMouseClicked
        // TODO add your handling code here:
        TelaCurso curso = new TelaCurso();
        curso.setVisible(true);
        desktop.add(curso);
    }//GEN-LAST:event_tabCursoMouseClicked

    private void tabVisitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabVisitaMouseClicked
        // TODO add your handling code here:
        TelaVisita visita = new TelaVisita();
        visita.setVisible(true);
        desktop.add(visita);
    }//GEN-LAST:event_tabVisitaMouseClicked

    private void mAdoçoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAdoçoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mAdoçoesActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
        
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Sair;
    private javax.swing.JMenu cadastro;
    private javax.swing.JMenuItem criança;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel kid1;
    private javax.swing.JLabel kid2;
    private javax.swing.JLabel kid3;
    private javax.swing.JLabel lblData;
    private javax.swing.JMenuItem mAdoçoes;
    public static javax.swing.JMenuItem mFuncionario;
    public static javax.swing.JMenu mRelatorio;
    private javax.swing.JMenu opçoes;
    private javax.swing.JMenuItem pais;
    private javax.swing.JTabbedPane tabCurso;
    private javax.swing.JTabbedPane tabFicha;
    private javax.swing.JTabbedPane tabVisita;
    // End of variables declaration//GEN-END:variables
}
