/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lardeApoio.janelas;

/**
 *
 * @author beatr
 *
 */
import java.sql.*;
import br.com.lardeApoio.camadadeacessoadados.ModulodeConexao;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class TelaFicha extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pcc = null;
    ResultSet rs = null;

    //RADIO BUTTON  APROVADO
    private String curso = "pendente";
    private String avaliacao = " pendente";
    private String genero;

    /**
     * Creates new form TelaCriança
     */
    public TelaFicha() {
        initComponents();
        conexao = ModulodeConexao.conexao();

    }

    private void pesquisar_pai() {
        String sql = "select idPais, nomePais, enderecoPais from pais where nomePais like ?";
        try {

            pcc = conexao.prepareStatement(sql);
            pcc.setString(1, txtNomePais.getText() + "%");
            rs = pcc.executeQuery();
            tblPais.setModel(DbUtils.resultSetToTableModel(rs));
            // EVENTO DIGITAR 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    private void campos() {

        int setar = tblPais.getSelectedRow();
        txtIdPais.setText(tblPais.getModel().getValueAt(setar, 0).toString());
    }

    private void ficha() {
        String sql = "insert into ficha (idadeMax, etnia, sexo, irmao, curso, avaliacao, idPais) values (?,?,?,?,?,?,?)";
        try {
            pcc = conexao.prepareStatement(sql);
            pcc.setString(1, txtIdadeCri.getText());
            pcc.setString(2, cbEtnia.getSelectedItem().toString());
            pcc.setString(3, genero);
            pcc.setString(4, txtIrmão.getText());
            pcc.setString(5, curso);
            pcc.setString(6, avaliacao);
            pcc.setString(7, txtIdPais.getText());
            
           
            //VALIDAÇÃO
            if ((txtIdadeCri.getText().isEmpty()) || (txtIrmão.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, " preencha os campos * ");
            } else {
                int add = pcc.executeUpdate();
                if (add > 0) {
                    JOptionPane.showMessageDialog(null, " adiocionado com sucesso");
                    txtIdadeCri.setText(null);

                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }

    private void pesquisar() {
        String idficha = JOptionPane.showInputDialog("ID Adoção");
        String sql = "select * from ficha where idFicha =" + idficha;
        try {
            pcc = conexao.prepareStatement(sql);
            //PREENCHE FORM
            rs = pcc.executeQuery();

            if (rs.next()) {
                txtId.setEnabled(false);
                txtId.setText(rs.getString(1));
                //RADIO BUTTON
                
                String rbCurso = rs.getString(7);
                if (rbCurso.equals("concluido")) {
                    btnCurso.setSelected(true);
                } else {
                    btnCurso.setSelected(false);
                }
                String rbAvaliacao = rs.getString(8);
                if (rbCurso.equals("aprovada")) {
                    btnAvaliacao.setSelected(true);
                    btnAvaliacao.setEnabled(false);
                } else {
                    btnAvaliacao.setSelected(false);
                }
                cbEtnia.setEnabled(false);
                cbEtnia.setSelectedItem(rs.getString(4));
                txtIdadeCri.setEnabled(false);
                txtIdadeCri.setText(rs.getString(3));
                String rbSexo = rs.getString(5);
                if (rbSexo.equals("Feminino")) {
                    cbSexoF.setSelected(true);
                } else {
                    cbSexoM.setSelected(true);
                }
                 txtIrmão.setEnabled(false);
                txtIrmão.setText(rs.getString(6));
                txtP1.setEnabled(false);
                txtP2.setEnabled(false);
                //String p = "select nome from pais where idpais =?";
                //pcc = conexao.prepareStatement(p);

                //txtP1.setText(rs.getString(1));
            } else {
                JOptionPane.showMessageDialog(null, " não encontrado");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbData = new javax.swing.JLabel();
        lbIdade = new javax.swing.JLabel();
        lbEtnia = new javax.swing.JLabel();
        txtIrmão = new javax.swing.JTextField();
        cbEtnia = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        txtIdPais = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPais = new javax.swing.JTable();
        txtNomePais = new javax.swing.JTextField();
        lbNome = new javax.swing.JLabel();
        progressbar = new javax.swing.JProgressBar();
        txtIdadeCri = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lbOS = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnAvaliacao = new javax.swing.JRadioButton();
        btnCurso = new javax.swing.JRadioButton();
        txtP1 = new javax.swing.JTextField();
        txtP2 = new javax.swing.JTextField();
        lbSexo = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        cbSexoF = new javax.swing.JRadioButton();
        cbSexoM = new javax.swing.JRadioButton();
        btnPesquisar = new javax.swing.JButton();

        setClosable(true);
        setForeground(java.awt.Color.orange);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ficha");
        setPreferredSize(new java.awt.Dimension(470, 568));
        setRequestFocusEnabled(false);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(470, 901));

        lbData.setText("Irmão");

        lbIdade.setText("Idade ");

        lbEtnia.setText("Etnia");

        txtIrmão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIrmãoActionPerformed(evt);
            }
        });

        cbEtnia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indigena", "Branco", "Preto", "Amarelo", "Pardo" }));
        cbEtnia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEtniaActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtIdPais.setText("  ");
        txtIdPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdPaisActionPerformed(evt);
            }
        });

        jLabel1.setText("* ID");

        tblPais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Parceiro"
            }
        ));
        tblPais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPaisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPais);

        txtNomePais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNomePaisKeyReleased(evt);
            }
        });

        lbNome.setText("Nome");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbNome)
                .addGap(18, 18, 18)
                .addComponent(txtNomePais, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdPais, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomePais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        progressbar.setPreferredSize(new java.awt.Dimension(148, 14));

        txtIdadeCri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdadeCriActionPerformed(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbOS.setText("Adoção n°");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        btnAvaliacao.setText("Avaliaçao");
        btnAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliacaoActionPerformed(evt);
            }
        });

        btnCurso.setText("Curso");
        btnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursoActionPerformed(evt);
            }
        });

        txtP1.setText(" ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 256, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbOS, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtP2)
                        .addComponent(txtP1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbOS)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(txtP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAvaliacao)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        lbSexo.setText("Sexo");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        cbSexoF.setText("F");
        cbSexoF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoFActionPerformed(evt);
            }
        });

        cbSexoM.setText("M");
        cbSexoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoMActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbIdade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(68, 68, 68))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbEtnia)
                                        .addComponent(lbSexo))
                                    .addComponent(lbData))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbEtnia, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtIrmão)
                                            .addComponent(txtIdadeCri)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbSexoF)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbSexoM)
                                        .addGap(0, 45, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(progressbar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdadeCri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbData)
                            .addComponent(txtIrmão, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEtnia)
                            .addComponent(cbEtnia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSexo)
                            .addComponent(cbSexoF)
                            .addComponent(cbSexoM))
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisar))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(progressbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(396, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setBounds(0, 0, 470, 568);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdadeCriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdadeCriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeCriActionPerformed

    private void txtIdPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPaisActionPerformed

    private void cbEtniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEtniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEtniaActionPerformed

    private void txtIrmãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIrmãoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIrmãoActionPerformed

    private void txtNomePaisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomePaisKeyReleased
        // TODO add your handling code here:
        // PESQUISAR PRETENDENTE POR NOME
        pesquisar_pai();
    }//GEN-LAST:event_txtNomePaisKeyReleased

    private void tblPaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPaisMouseClicked
        // TODO add your handling code here:
        //CLICAR NA LINHA
        campos();
    }//GEN-LAST:event_tblPaisMouseClicked

    private void btnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursoActionPerformed
        // TODO add your handling code here:
        curso = "concluido";
    }//GEN-LAST:event_btnCursoActionPerformed

    private void btnAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliacaoActionPerformed
        // TODO add your handling code here:
        avaliacao = "Aprovado";
    }//GEN-LAST:event_btnAvaliacaoActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        btnCurso.setSelected(true);

    }//GEN-LAST:event_formInternalFrameOpened

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        ficha();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void cbSexoFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoFActionPerformed
        // TODO add your handling code here:
        genero = "Feminino";
    }//GEN-LAST:event_cbSexoFActionPerformed

    private void cbSexoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoMActionPerformed
        // TODO add your handling code here:
        genero = "Masculino";
    }//GEN-LAST:event_cbSexoMActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        pesquisar();
    }//GEN-LAST:event_btnPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnAvaliacao;
    private javax.swing.JRadioButton btnCurso;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbEtnia;
    private javax.swing.JRadioButton cbSexoF;
    private javax.swing.JRadioButton cbSexoM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbEtnia;
    private javax.swing.JLabel lbIdade;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbOS;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JProgressBar progressbar;
    private javax.swing.JTable tblPais;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdPais;
    private javax.swing.JTextField txtIdadeCri;
    private javax.swing.JTextField txtIrmão;
    private javax.swing.JTextField txtNomePais;
    private javax.swing.JTextField txtP1;
    private javax.swing.JTextField txtP2;
    // End of variables declaration//GEN-END:variables
}
